<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\RaceIntelligence.Identity.Api\RaceIntelligence.Identity.Api.csproj" />
    <ProjectReference Include="..\RaceIntelligence.Ingest.RaceRoom\RaceIntelligence.Ingest.RaceRoom.csproj" />
    <ProjectReference Include="..\RaceIntelligence.Collector\RaceIntelligence.Collector.csproj" />
    <ProjectReference Include="..\RaceIntelligence.Web\RaceIntelligence.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>0c7d49b7-54f9-428f-a25c-80816c22e7df</UserSecretsId>
  </PropertyGroup>

</Project>
