// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaceIntelligence.Persistence;

#nullable disable

namespace RaceIntelligence.Persistence.Migrations
{
    [DbContext(typeof(RaceIntelligenceDbContext))]
    partial class RaceIntelligenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CarClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_class_id");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SimCarId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sim_car_id");

                    b.HasKey("Id");

                    b.HasIndex("CarClassId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SimCarId")
                        .IsUnique();

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.CarClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("car_classes", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("SimDriverId")
                        .HasColumnType("text")
                        .HasColumnName("sim_driver_id");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasFilter("sim_driver_id IS NULL");

                    b.HasIndex("SimDriverId")
                        .IsUnique();

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.GameVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ApiVersionMajor")
                        .HasColumnType("integer")
                        .HasColumnName("api_version_major");

                    b.Property<int>("ApiVersionMinor")
                        .HasColumnType("integer")
                        .HasColumnName("api_version_minor");

                    b.Property<string>("ConnectorVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connector_version");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("GameVersionText")
                        .HasColumnType("text")
                        .HasColumnName("game_version");

                    b.HasKey("Id");

                    b.HasIndex("GameVersionText", "ApiVersionMajor", "ApiVersionMinor", "ConnectorVersion")
                        .IsUnique();

                    b.ToTable("game_versions", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Lap", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lap_number");

                    b.Property<float?>("AvgSpeed")
                        .HasColumnType("real")
                        .HasColumnName("avg_speed");

                    b.Property<float?>("FuelUsed")
                        .HasColumnType("real")
                        .HasColumnName("fuel_used");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<TimeSpan?>("LapTime")
                        .HasColumnType("interval")
                        .HasColumnName("lap_time");

                    b.Property<float?>("MaxSpeed")
                        .HasColumnType("real")
                        .HasColumnName("max_speed");

                    b.Property<float?>("QualityScore")
                        .HasColumnType("real")
                        .HasColumnName("quality_score");

                    b.HasKey("SessionId", "LapNumber");

                    b.ToTable("laps", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Capabilities")
                        .HasColumnType("bigint")
                        .HasColumnName("capabilities");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Extras")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extras");

                    b.Property<short?>("FuelUsageRate")
                        .HasColumnType("smallint")
                        .HasColumnName("fuel_usage_rate");

                    b.Property<Guid>("GameVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_version_id");

                    b.Property<string>("PlayerName")
                        .HasColumnType("text")
                        .HasColumnName("player_name");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<short>("SessionType")
                        .HasColumnType("smallint")
                        .HasColumnName("session_type");

                    b.Property<string>("Setup")
                        .HasColumnType("jsonb")
                        .HasColumnName("setup");

                    b.Property<string>("SimCarClassId")
                        .HasColumnType("text")
                        .HasColumnName("sim_car_class_id");

                    b.Property<string>("SimCarId")
                        .HasColumnType("text")
                        .HasColumnName("sim_car_id");

                    b.Property<string>("SimManufacturerId")
                        .HasColumnType("text")
                        .HasColumnName("sim_manufacturer_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("TrackLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_layout_id");

                    b.Property<short?>("TyreWearRate")
                        .HasColumnType("smallint")
                        .HasColumnName("tyre_wear_rate");

                    b.Property<string>("Weather")
                        .HasColumnType("jsonb")
                        .HasColumnName("weather");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("GameVersionId")
                        .HasDatabaseName("ix_sessions_game_version");

                    b.HasIndex("TrackLayoutId");

                    b.HasIndex("DriverId", "TyreWearRate", "FuelUsageRate")
                        .HasDatabaseName("ix_sessions_driver_wear_rates");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.TelemetrySample", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<float?>("Brake")
                        .HasColumnType("real")
                        .HasColumnName("brake");

                    b.Property<float?>("Clutch")
                        .HasColumnType("real")
                        .HasColumnName("clutch");

                    b.Property<float>("EngineRpm")
                        .HasColumnType("real")
                        .HasColumnName("engine_rpm");

                    b.Property<string>("Extras")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extras");

                    b.Property<float>("FuelLeft")
                        .HasColumnType("real")
                        .HasColumnName("fuel_left");

                    b.Property<short?>("Gear")
                        .HasColumnType("smallint")
                        .HasColumnName("gear");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lap_number");

                    b.Property<short?>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.Property<int>("Sector")
                        .HasColumnType("integer")
                        .HasColumnName("sector");

                    b.Property<double>("SimulationTime")
                        .HasColumnType("double precision")
                        .HasColumnName("simulation_time");

                    b.Property<float>("Speed")
                        .HasColumnType("real")
                        .HasColumnName("speed");

                    b.Property<float>("Steering")
                        .HasColumnType("real")
                        .HasColumnName("steering");

                    b.PrimitiveCollection<float[]>("SuspensionTravel")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("suspension_travel");

                    b.Property<float?>("Throttle")
                        .HasColumnType("real")
                        .HasColumnName("throttle");

                    b.Property<float?>("TrackPositionFraction")
                        .HasColumnType("real")
                        .HasColumnName("track_position_fraction");

                    b.PrimitiveCollection<float?[]>("TyrePressure")
                        .HasColumnType("real[]")
                        .HasColumnName("tyre_pressure");

                    b.Property<string>("TyreTemperature")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tyre_temperature");

                    b.PrimitiveCollection<float?[]>("TyreWear")
                        .HasColumnType("real[]")
                        .HasColumnName("tyre_wear");

                    b.PrimitiveCollection<float[]>("WheelSpeed")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("wheel_speed");

                    b.HasKey("SessionId", "Timestamp", "SequenceNumber");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_telemetry_timestamp_brin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Timestamp"), "brin");

                    b.HasIndex("SessionId", "LapNumber")
                        .HasDatabaseName("ix_telemetry_session_lap");

                    b.ToTable("telemetry_samples", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.TrackLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("LengthMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("length_meters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "Name")
                        .IsUnique();

                    b.ToTable("track_layouts", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Car", b =>
                {
                    b.HasOne("RaceIntelligence.Persistence.Entities.CarClass", "CarClass")
                        .WithMany("Cars")
                        .HasForeignKey("CarClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaceIntelligence.Persistence.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CarClass");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Lap", b =>
                {
                    b.HasOne("RaceIntelligence.Persistence.Entities.Session", "Session")
                        .WithMany("Laps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Session", b =>
                {
                    b.HasOne("RaceIntelligence.Persistence.Entities.Car", "Car")
                        .WithMany("Sessions")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaceIntelligence.Persistence.Entities.Driver", "Driver")
                        .WithMany("Sessions")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaceIntelligence.Persistence.Entities.GameVersion", "GameVersion")
                        .WithMany("Sessions")
                        .HasForeignKey("GameVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceIntelligence.Persistence.Entities.TrackLayout", "TrackLayout")
                        .WithMany("Sessions")
                        .HasForeignKey("TrackLayoutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Car");

                    b.Navigation("Driver");

                    b.Navigation("GameVersion");

                    b.Navigation("TrackLayout");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.TelemetrySample", b =>
                {
                    b.HasOne("RaceIntelligence.Persistence.Entities.Session", "Session")
                        .WithMany("TelemetrySamples")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.TrackLayout", b =>
                {
                    b.HasOne("RaceIntelligence.Persistence.Entities.Track", "Track")
                        .WithMany("Layouts")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Car", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.CarClass", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Driver", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.GameVersion", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Manufacturer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Session", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("TelemetrySamples");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.Track", b =>
                {
                    b.Navigation("Layouts");
                });

            modelBuilder.Entity("RaceIntelligence.Persistence.Entities.TrackLayout", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
