// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaceIntelligence.Identity;

#nullable disable

namespace RaceIntelligence.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaceIntelligence.Identity.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Identity.Entities.PersonSimAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("SimDriverId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sim_driver_id");

                    b.Property<string>("SimKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sim_key");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SimKey", "SimDriverId")
                        .IsUnique();

                    b.ToTable("person_sim_alias", (string)null);
                });

            modelBuilder.Entity("RaceIntelligence.Identity.Entities.PersonSimAlias", b =>
                {
                    b.HasOne("RaceIntelligence.Identity.Entities.Person", "Person")
                        .WithMany("Aliases")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RaceIntelligence.Identity.Entities.Person", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
