/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as RoomsRoomIdDriverKeyRouteImport } from './routes/rooms.$roomId.$driverKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdDriverKeyRoute = RoomsRoomIdDriverKeyRouteImport.update({
  id: '/$driverKey',
  path: '/$driverKey',
  getParentRoute: () => RoomsRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/$driverKey': typeof RoomsRoomIdDriverKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/$driverKey': typeof RoomsRoomIdDriverKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdRouteWithChildren
  '/rooms/$roomId/$driverKey': typeof RoomsRoomIdDriverKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rooms/$roomId' | '/rooms/$roomId/$driverKey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rooms/$roomId' | '/rooms/$roomId/$driverKey'
  id: '__root__' | '/' | '/rooms/$roomId' | '/rooms/$roomId/$driverKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/$driverKey': {
      id: '/rooms/$roomId/$driverKey'
      path: '/$driverKey'
      fullPath: '/rooms/$roomId/$driverKey'
      preLoaderRoute: typeof RoomsRoomIdDriverKeyRouteImport
      parentRoute: typeof RoomsRoomIdRoute
    }
  }
}

interface RoomsRoomIdRouteChildren {
  RoomsRoomIdDriverKeyRoute: typeof RoomsRoomIdDriverKeyRoute
}

const RoomsRoomIdRouteChildren: RoomsRoomIdRouteChildren = {
  RoomsRoomIdDriverKeyRoute: RoomsRoomIdDriverKeyRoute,
}

const RoomsRoomIdRouteWithChildren = RoomsRoomIdRoute._addFileChildren(
  RoomsRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsRoomIdRoute: RoomsRoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
