import {
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
  RouterProvider,
} from '@tanstack/react-router';
import { act, render } from '@testing-library/react';
import { ROUTER_DEFAULTS } from '../router';
import { FocusView } from '../features/focus/FocusView';
import { RoomsView } from '../features/rooms/RoomsView';
import { SessionView } from '../features/tower/SessionView';
import { LiveProvider } from '../shared/live/LiveProvider';
import { AppShell } from '../shared/ui/AppShell';

/**
 * Mounts the app at a given URL, on an in-memory history.
 *
 * The route tree is built here rather than imported from `routeTree.gen.ts` because that file is
 * generated by the TanStack Start Vite plugin, which the test config deliberately does not load —
 * see `vitest.config.ts`. The shape below mirrors `app/routes/` exactly, and it is small enough
 * that a divergence is visible at a glance; what it buys is tests that run against components
 * rather than against a build step.
 */
function buildRouteTree() {
  const rootRoute = createRootRoute({
    component: () => (
      <LiveProvider>
        <AppShell>
          <Outlet />
        </AppShell>
      </LiveProvider>
    ),
  });

  const indexRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/',
    component: RoomsView,
  });

  const sessionRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/rooms/$roomId',
    component: SessionView,
  });

  const focusRoute = createRoute({
    getParentRoute: () => sessionRoute,
    path: '$driverKey',
    component: FocusView,
  });

  return rootRoute.addChildren([indexRoute, sessionRoute.addChildren([focusRoute])]);
}

/**
 * Renders the app at `initialPath`, returning the router so a test can read the URL back.
 *
 * Awaits `router.load()` first: matching a route is asynchronous, and rendering without it puts an
 * empty div on screen and nothing else — including no `LiveProvider`, and therefore no socket.
 */
export async function renderApp(initialPath = '/') {
  const router = createRouter({
    routeTree: buildRouteTree(),
    history: createMemoryHistory({ initialEntries: [initialPath] }),
    ...ROUTER_DEFAULTS,
  });

  await router.load();

  const rendered = await act(async () => render(<RouterProvider router={router} />));

  return {
    router,
    ...rendered,
    currentPath: () => router.state.location.pathname,
  };
}
