using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RaceIntelligence.RaceRoom.Channels.Generator;

/// <summary>
/// Emits every hand-kept restatement of RaceRoom's telemetry channels from one manifest.
/// </summary>
/// <remarks>
/// <para>
/// The manifest is <c>channels/raceroom-telemetry.channels</c>, supplied to each consuming project
/// as an <c>AdditionalFiles</c> item. A project opts in by declaring a partial type carrying
/// <c>[GeneratedFromChannels(ChannelArtifact.X)]</c>; the attribute and its enum are injected into
/// every referencing compilation, so nothing needs a runtime package to use this.
/// </para>
/// <para>
/// <b>Why generate rather than hand-write with a test.</b> The bulk writer names its columns in one
/// list and writes their values in another, positionally. Postgres binary <c>COPY</c> does not
/// check the two agree — a mismatch writes camber into ride height and reports success. A test can
/// notice that afterwards; a single loop over a single list cannot express it at all.
/// </para>
/// </remarks>
[Generator(Microsoft.CodeAnalysis.LanguageNames.CSharp)]
public sealed class ChannelSourceGenerator : IIncrementalGenerator
{
    private const string ManifestFileName = "raceroom-telemetry.channels";
    private const string AttributeName = "RaceIntelligence.RaceRoom.Channels.GeneratedFromChannelsAttribute";

    private static readonly DiagnosticDescriptor MissingManifest = new(
        id: "RRCH001",
        title: "The RaceRoom channel manifest is missing",
        messageFormat: "No AdditionalFiles item named '" + ManifestFileName + "' was supplied, so no channels could be generated",
        category: "RaceRoomChannels",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MalformedManifest = new(
        id: "RRCH002",
        title: "The RaceRoom channel manifest is malformed",
        messageFormat: "{0}",
        category: "RaceRoomChannels",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ChannelArtifact.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var manifest = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(ManifestFileName, StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => file.GetText(ct)?.ToString() ?? string.Empty)
            .Collect();

        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => Target.From(ctx))
            .Where(static target => target is not null)
            .Collect();

        context.RegisterSourceOutput(manifest.Combine(targets), static (ctx, pair) => Emit(ctx, pair.Left, pair.Right));
    }

    private static void Emit(
        SourceProductionContext context,
        ImmutableArray<string> manifestTexts,
        ImmutableArray<Target> targets)
    {
        if (targets.Length == 0)
        {
            return;
        }

        if (manifestTexts.Length == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingManifest, Location.None));
            return;
        }

        var channels = ChannelManifestParser.Parse(manifestTexts[0], out var errors);
        if (errors.Count > 0)
        {
            foreach (var error in errors)
            {
                context.ReportDiagnostic(Diagnostic.Create(MalformedManifest, Location.None, error));
            }

            return;
        }

        foreach (var target in targets)
        {
            var source = target.Artifact switch
            {
                "WireDto" => WireDtoEmitter.Emit(target, channels),
                "Entity" => EntityEmitter.Emit(target, channels),
                "Manifest" => ManifestEmitter.Emit(target, channels),
                _ => null,
            };

            if (source is not null)
            {
                context.AddSource(target.TypeName + "." + target.Artifact + ".g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }
    }

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace RaceIntelligence.RaceRoom.Channels;

        /// <summary>Which restatement of the channel manifest to generate into this partial type.</summary>
        internal enum ChannelArtifact
        {
            /// <summary>MessagePack members, keyed by manifest position.</summary>
            WireDto,

            /// <summary>
            /// Storage properties, the ordered column list, the binary <c>COPY</c> row writer built
            /// from that same list, and the EF Core column configuration.
            /// </summary>
            Entity,

            /// <summary>Names, columns and groups, for the read API's allowlist and for tests.</summary>
            Manifest,
        }

        /// <summary>
        /// Marks a partial type as generated from <c>channels/raceroom-telemetry.channels</c>.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
        internal sealed class GeneratedFromChannelsAttribute : global::System.Attribute
        {
            public GeneratedFromChannelsAttribute(ChannelArtifact artifact) => Artifact = artifact;

            public ChannelArtifact Artifact { get; }

            /// <summary>
            /// For <see cref="ChannelArtifact.Entity"/>: the wire DTO to generate a converter from.
            /// Fully qualified, and left null when the consuming project has no wire type in scope.
            /// </summary>
            public string? Companion { get; set; }
        }
        """;
}

/// <summary>One partial type asking for one artifact.</summary>
internal sealed class Target
{
    private Target(string ns, string typeName, string keyword, string artifact, string companion)
    {
        Namespace = ns;
        TypeName = typeName;
        Keyword = keyword;
        Artifact = artifact;
        Companion = companion;
    }

    public string Namespace { get; }

    public string TypeName { get; }

    /// <summary>
    /// The declaration as written, with <c>partial</c> inserted where C# requires it — e.g.
    /// <c>public sealed partial record</c>.
    /// </summary>
    public string Keyword { get; }

    public string Artifact { get; }

    public string Companion { get; }

    public static Target From(GeneratorAttributeSyntaxContext ctx)
    {
        var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var attribute = ctx.Attributes[0];

        var artifact = "";
        if (attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is int value)
        {
            artifact = value switch { 0 => "WireDto", 1 => "Entity", 2 => "Manifest", _ => "" };
        }

        var companion = "";
        foreach (var named in attribute.NamedArguments)
        {
            if (named.Key == "Companion" && named.Value.Value is string text)
            {
                companion = text;
            }
        }

        var declaration = (TypeDeclarationSyntax)ctx.TargetNode;
        var modifiers = string.Join(
            " ",
            declaration.Modifiers.Select(m => m.ValueText).Where(m => m != "partial"));
        var keyword = (modifiers.Length > 0 ? modifiers + " " : "") + "partial " + declaration.Keyword.ValueText;

        return new Target(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            keyword,
            artifact,
            companion);
    }
}
