using System;
using System.Collections.Generic;
using System.Text;

namespace RaceIntelligence.RaceRoom.Channels.Generator;

internal static class Source
{
    public static StringBuilder Header(Target target)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("// Generated from channels/raceroom-telemetry.channels. Edit that file, not this one.");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(target.Namespace).AppendLine(";");
        builder.AppendLine();
        return builder;
    }

    /// <summary>The Npgsql type code for a PostgreSQL type named in the manifest.</summary>
    public static string NpgsqlDbType(string storeType) => storeType switch
    {
        "uuid" => "Uuid",
        "timestamp with time zone" => "TimestampTz",
        "bigint" => "Bigint",
        "double precision" => "Double",
        "integer" => "Integer",
        "real" => "Real",
        "smallint" => "Smallint",
        "boolean" => "Boolean",
        _ => throw new InvalidOperationException("No Npgsql type is mapped for '" + storeType + "'."),
    };
}

/// <summary>The ingest wire: one MessagePack member per channel, keyed by manifest position.</summary>
internal static class WireDtoEmitter
{
    public static string Emit(Target target, IReadOnlyList<Channel> channels)
    {
        var builder = Source.Header(target);

        builder.AppendLine("[global::MessagePack.MessagePackObject]");
        builder.Append(target.Keyword).Append(' ').AppendLine(target.TypeName);
        builder.AppendLine("{");

        foreach (var channel in channels)
        {
            AppendDoc(builder, channel);
            builder.Append("    [global::MessagePack.Key(").Append(channel.Index).AppendLine(")]");
            builder.Append("    public ").Append(channel.ClrType).Append(' ').Append(channel.PropertyName)
                   .AppendLine(" { get; init; }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendDoc(StringBuilder builder, Channel channel) =>
        builder.Append("    /// <summary>Column <c>").Append(channel.Column)
               .Append("</c>, group <c>").Append(channel.Group).AppendLine("</c>.</summary>");
}

/// <summary>
/// Storage: the properties, the ordered column list, the binary <c>COPY</c> row writer built from
/// that same list in the same loop, and the EF Core column configuration.
/// </summary>
internal static class EntityEmitter
{
    public static string Emit(Target target, IReadOnlyList<Channel> channels)
    {
        var builder = Source.Header(target);

        // HasColumnName and friends are relational extension methods, so this one using is not
        // optional the way a fully-qualified type name would be.
        builder.AppendLine("using Microsoft.EntityFrameworkCore;");
        builder.AppendLine();
        builder.Append(target.Keyword).Append(' ').AppendLine(target.TypeName);
        builder.AppendLine("{");

        foreach (var channel in channels)
        {
            builder.Append("    /// <summary>Column <c>").Append(channel.Column)
                   .Append("</c>, group <c>").Append(channel.Group).AppendLine("</c>.</summary>");
            builder.Append("    public ").Append(channel.ClrType).Append(' ').Append(channel.PropertyName)
                   .AppendLine(" { get; init; }");
            builder.AppendLine();
        }

        // Columns and the write order below come out of one loop over one list, which is the whole
        // reason this file is generated. Binary COPY writes into whatever column sits at each
        // position, so a hand-kept pair of lists fails by corrupting data rather than by throwing.
        builder.AppendLine("    /// <summary>Every column of <c>telemetry_samples</c>, in table order.</summary>");
        builder.AppendLine("    public static readonly string[] Columns =");
        builder.AppendLine("    [");
        foreach (var channel in channels)
        {
            builder.Append("        \"").Append(channel.Column).AppendLine("\",");
        }

        builder.AppendLine("    ];");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>The same columns, comma-separated, for a COPY or INSERT column list.</summary>");
        builder.AppendLine("    public static readonly string ColumnList = string.Join(\", \", Columns);");
        builder.AppendLine();

        EmitCopyRow(builder, channels);
        EmitConfiguration(builder, channels);

        if (target.Companion.Length > 0)
        {
            EmitFromDto(builder, target, channels);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitCopyRow(StringBuilder builder, IReadOnlyList<Channel> channels)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Writes this sample as one binary <c>COPY</c> row, in <see cref=\"Columns\"/> order.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public async global::System.Threading.Tasks.Task CopyRowAsync(");
        builder.AppendLine("        global::Npgsql.NpgsqlBinaryImporter importer,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        await importer.StartRowAsync(ct).ConfigureAwait(false);");

        foreach (var channel in channels)
        {
            var type = "global::NpgsqlTypes.NpgsqlDbType." + Source.NpgsqlDbType(channel.StoreType);

            if (channel.IsNullable)
            {
                var local = "value" + channel.Index;
                builder.Append("        if (").Append(channel.PropertyName).Append(" is { } ").Append(local).AppendLine(")");
                builder.AppendLine("        {");
                builder.Append("            await importer.WriteAsync(").Append(local)
                       .Append(", ").Append(type).AppendLine(", ct).ConfigureAwait(false);");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                builder.AppendLine("            await importer.WriteNullAsync(ct).ConfigureAwait(false);");
                builder.AppendLine("        }");
            }
            else
            {
                builder.Append("        await importer.WriteAsync(").Append(channel.PropertyName)
                       .Append(", ").Append(type).AppendLine(", ct).ConfigureAwait(false);");
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitConfiguration(StringBuilder builder, IReadOnlyList<Channel> channels)
    {
        builder.AppendLine("    /// <summary>Maps every channel property to its column. Called from the entity configuration.</summary>");
        builder.AppendLine("    public static void ConfigureChannels<TEntity>(");
        builder.AppendLine("        global::Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity> builder)");
        builder.AppendLine("        where TEntity : class");
        builder.AppendLine("    {");
        foreach (var channel in channels)
        {
            builder.Append("        builder.Property(\"").Append(channel.PropertyName)
                   .Append("\").HasColumnName(\"").Append(channel.Column)
                   .Append("\").HasColumnType(\"").Append(channel.StoreType)
                   .Append("\").IsRequired(").Append(channel.IsNullable ? "false" : "true").AppendLine(");");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitFromDto(StringBuilder builder, Target target, IReadOnlyList<Channel> channels)
    {
        builder.AppendLine("    /// <summary>Copies every channel across from the ingest wire, field for field.</summary>");
        builder.Append("    public static ").Append(target.TypeName).Append(" FromDto(global::")
               .Append(target.Companion).AppendLine(" dto) => new()");
        builder.AppendLine("    {");
        foreach (var channel in channels)
        {
            builder.Append("        ").Append(channel.PropertyName).Append(" = dto.")
                   .Append(channel.PropertyName).AppendLine(",");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
    }
}

/// <summary>Names, columns and groups — what the read API validates <c>?channels=</c> against.</summary>
internal static class ManifestEmitter
{
    public static string Emit(Target target, IReadOnlyList<Channel> channels)
    {
        var builder = Source.Header(target);

        builder.Append(target.Keyword).Append(' ').AppendLine(target.TypeName);
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>One channel: its wire name, its column, and the group it belongs to.</summary>");
        builder.AppendLine("    public readonly record struct Channel(string Name, string Column, string Group, string StoreType, bool IsNullable);");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Every channel, in manifest order — which is MessagePack key order and column order.</summary>");
        builder.AppendLine("    public static readonly global::System.Collections.Generic.IReadOnlyList<Channel> All =");
        builder.AppendLine("    [");
        foreach (var channel in channels)
        {
            builder.Append("        new(\"").Append(channel.Name)
                   .Append("\", \"").Append(channel.Column)
                   .Append("\", \"").Append(channel.Group)
                   .Append("\", \"").Append(channel.StoreType)
                   .Append("\", ").Append(channel.IsNullable ? "true" : "false").AppendLine("),");
        }

        builder.AppendLine("    ];");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Channels by wire name, for validating a <c>?channels=</c> list.</summary>");
        builder.AppendLine("    public static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, Channel> ByName =");
        builder.AppendLine("        global::System.Linq.Enumerable.ToDictionary(All, static c => c.Name, global::System.StringComparer.Ordinal);");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Channel names by group, for the coarse selectors a widget asks in.</summary>");
        builder.AppendLine("    public static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Collections.Generic.IReadOnlyList<string>> ByGroup =");
        builder.AppendLine("        global::System.Linq.Enumerable.ToDictionary(");
        builder.AppendLine("            global::System.Linq.Enumerable.GroupBy(All, static c => c.Group),");
        builder.AppendLine("            static g => g.Key,");
        builder.AppendLine("            static g => (global::System.Collections.Generic.IReadOnlyList<string>)global::System.Linq.Enumerable.ToArray(");
        builder.AppendLine("                global::System.Linq.Enumerable.Select(g, static c => c.Name)),");
        builder.AppendLine("            global::System.StringComparer.Ordinal);");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
