<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RaceIntelligence.Core\RaceIntelligence.Core.csproj" />
    <ProjectReference Include="..\RaceIntelligence.RaceRoom.Telemetry\RaceIntelligence.RaceRoom.Telemetry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>

</Project>
